= Lab 2: Project Price Alert

Using BigData analyses we've discovered certain behavioural patterns in customers visiting our site.
In this case we could point out daily visits to the same products by the same customer without actually buying anything.
Then,
when there was a price drop or the availability of the product changed,
the purchase was done.

We could distinguish two types of customers:

* The first type of customers are mostly moms and dads, with newborn children,
  usually visit in the morning between 09:00-11:00h and 13:00-15:00h.
  They are looking mostly for diapers and baby wipes.
  Statistical analyses shows that this is usually the time that babies take a nap
* The second group consist of students mostly between the age of 18 and 26 years.
  Their interest mainly go out to consoles and (computer)games.
  Since the release of the Nintendo Switch this behaviour has quadrupled.
  Interestingly enough they are active at the same time periods the young parents are,
  even though that is the same time as college is...

After doing marketing research and crunching more BigData,
our Business Analysts have come to the conclusion that if we offer a price-drop notification service:

* Customers no longer need to refresh the same page every day.
  They can simply wait for the notification in their email and then instantly buy the product
* Young parents will be able to get some sleep while their toddlers sleep,
  so they'll be happier and eventually we estimate that they will buy more products at our store
* Students will either be able to attend college,
  sleep more or do both (inconclusive due to insufficient data for analyses)
* We will be able to analyse what customers are actually willing to pay for a product and make sharper offers

Your team has been assigned to create a technical solution for this opportunity.

== Acceptance criteria

* Customers are able to register for a price drop.
  Customers are identified by their email address
* When the price drops below a given threshold,
  an email is send out to the customer.
** The email will contain the new price and a link to the product page
** The email is only sent to the customer once,
   even if the price raises and drops below the threshold again
* Customers are able to create notifications for different products,
  but only for one price per product.
  If a notification is created for a product that is already registered to that customer,
  the existing notification will be updated
* Customers will also be able to remove notifications,
  for when they are no longer interested in the product

== Non-functional requirements

* At bol.com we have a
  https://martinfowler.com/articles/microservices.html[microservice architecture].
  So the component your team will build should fit in that landscape
* Most of the services at bol.com are written in Java,
  therefore the new service must be built using Java 8
* There are two backend services you will need to talk to (stubs are provided):
** The 'Product Service' which will have an API call to get the price of a certain product.
  A product is identified by an EAN (European Article Number)
** The 'Messaging Service' which will have an API call to send an email to the customer
* To decrease the footprint of our infrastructure,
  we are experimenting with running java applications stand-alone.
  Therefore the result of your project should be a jar file which can be run with the command:
+
----
java -jar server.jar
----
* Your application should be configurable using a properties file (`server.properties`)
  that resides in the same directory as the jar file.
  These properties must be used to configure the listening port of your service,
  and where it can find its dependencies.
  So the properties file should at least contain the following entries:
+
----
server.port=8080

server.emailservice.host=localhost
server.emailservice.port=8180

server.productservice.host=localhost
server.productservice.port=8280
----
* For this version of the service it can be non-persistent.
  So it will be sufficient to store the results in memory
* *(Important!)* All (design) decisions you take,
  with reasonings,
  must be written in a `decisions.txt` file
* *(Important!)* The service must be able to handle concurrent API calls,
  even for the same customer and the same product,
  without causing any data inconsistencies.
  Data inconsistencies that pop up during testing are unacceptable and will fail the project
- The frontend is built by another team.
  Your focus is on writing a backend REST service.
  The design of the frontend API is a given

== Bonus features

* *(Optionally)* For testing or demo purposes you can write a frontend for your service.
  This frontend must not be part of the `server.jar`.
  Instead of that it will be named `frontend.jar` and the browse-url must be http://localhost:80/.
  Clear instructions must be included in the `decisions.txt` file
* *(Optionally)* You are allowed to store the results on disk.
  The database file should be named `server.db`.
  Data must then be read and written using the `java.io.RandomAccessFile` class.
  Please note that this could be an extra risk in regards to data (in)consistency...
