= Lab 2: Project Price Alert

Using BigData analyses we've discovered certain behavioural patterns in customers visiting our site.
In this case we could point out daily visits to the same products by the same customer without actually buying anything.
Then,
when there was a price drop or the availability of the product changed,
the purchase was done.

We could distinguish two types of customers:

* The first type of customers are mostly moms and dads, with newborn children,
  usually visit in the morning between 09:00-11:00h and 13:00-15:00h.
  They are looking mostly for diapers and baby wipes.
  Statistical analyses shows that this is usually the time that babies take a nap
* The second group consist of students mostly between the age of 18 and 26 years.
  Their interest mainly go out to consoles and (computer)games.
  Since the release of the Nintendo Switch this behaviour has quadrupled.
  Interestingly enough they are active at the same time periods the young parents are,
  even though that is the same time as college is...

After doing marketing research and crunching more BigData,
our Business Analysts have come to the conclusion that if we offer a price-drop notification service:

* Customers no longer need to refresh the same page every day.
  They can simply wait for the notification in their email and then instantly buy the product
* Young parents will be able to get some sleep while their toddlers sleep,
  so they'll be happier and eventually we estimate that they will buy more products at our store
* Students will either be able to attend college,
  sleep more or do both (inconclusive due to insufficient data for analyses)
* We will be able to analyse what customers are actually willing to pay for a product and make sharper offers

Your team has been assigned to create a technical solution for this opportunity.

In `labs/02-homework` you can find the homework lab.

.Project structure
----
.
├── stubs
│   ├── customerservice
│   │   ├── src
│   │   │   ├── dist
│   │   │   │   └── customerservice.yaml
│   │   │   └── main
│   │   │       └── java
│   │   │           └── com
│   │   │               └── bol
│   │   │                   └── customerservice
│   │   │                       ├── api
│   │   │                       │   └── Customer.java
│   │   │                       ├── health
│   │   │                       │   └── V1ApiHealthCheck.java
│   │   │                       ├── jdbi
│   │   │                       │   └── CustomerDao.java
│   │   │                       ├── resources
│   │   │                       │   └── CustomerServiceResource.java
│   │   │                       ├── CustomerServiceApplication.java
│   │   │                       └── CustomerServiceConfiguration.java
│   │   └── customerservice.gradle
│   ├── emailservice
│   │   ├── src
│   │   │   ├── dist
│   │   │   │   └── emailservice.yaml
│   │   │   └── main
│   │   │       └── java
│   │   │           └── com
│   │   │               └── bol
│   │   │                   └── emailservice
│   │   │                       ├── api
│   │   │                       │   └── Email.java
│   │   │                       ├── health
│   │   │                       │   └── V1ApiHealthCheck.java
│   │   │                       ├── resources
│   │   │                       │   └── EmailServiceResource.java
│   │   │                       ├── EmailServiceApplication.java
│   │   │                       └── EmailServiceConfiguration.java
│   │   └── emailservice.gradle
│   └── productservice
│       ├── src
│       │   ├── dist
│       │   │   └── productservice.yaml
│       │   └── main
│       │       └── java
│       │           └── com
│       │               └── bol
│       │                   └── productservice
│       │                       ├── api
│       │                       │   └── Product.java
│       │                       ├── health
│       │                       │   └── V1ApiHealthCheck.java
│       │                       ├── jdbi
│       │                       │   └── ProductDao.java
│       │                       ├── resources
│       │                       │   └── ProductServiceResource.java
│       │                       ├── ProductServiceApplication.java
│       │                       └── ProductServiceConfiguration.java
│       └── productservice.gradle
├── 02-homework.gradle
├── price-notification-service.xsd
└── README.adoc
----

== Acceptance criteria

* Customers are able to register for a price drop
* Customers are identified by their email address
* When the price drops below a given threshold,
  an email is send out to the customer
** The email will contain the new price and a link to the product page. 
 Links to the productpage are formatted like this:
 `https://www.bol.com/nl/p/{title}/{ean}/`
** The email is only sent to the customer once,
   even if the price raises and drops below the threshold again
* Customers are able to create notifications for different products,
  but only for one price per product.
  If a notification is created for a product that is already registered to that customer,
  the existing notification will be updated
* Customers will also be able to remove notifications,
  for when they are no longer interested in the product

== Non-functional requirements

* At bol.com we have a
  https://martinfowler.com/articles/microservices.html[microservice architecture].
  So the component your team will build should fit in that landscape.
  Also take into account that some services may act up by throwing server errors at you,
  responding slow or may not be available at all. Write your code defensively
* Most of the services at bol.com are written in Java,
  therefore the new service must be built using Java 8
* There are three backend services you will need to talk to (The source code for the stubs is provided):
** The 'Product Service' which will have an API call to get the price of a certain product.
  A product is identified by an EAN (European Article Number)
** The 'Customer Service' which will have an API call to get customer information (name, email)
  A customer is identified by an internal customerId
** The 'Email Service' which will have an API call to send an email to the customer
* To decrease the footprint of our infrastructure,
  we are experimenting with running java applications stand-alone.
  Therefor the result of your project should be a stand-alone java application,
  which is runnable via single command
  (eg. `java -jar server.jar`, or `./my-service`)
* Your service should be configurable using a configuration file (eg. `.properties` or `.yaml`). +
  The following things should be configurable:
** The port your service API is available on
** The host and port for each service your service is dependent on
* Changes must be persistent - so if you restart your service any previously registered notifications
  will still be available. 
** Your service needs to store its data in a file called 'service.db'. 
** Data should be read and written using Java's 'java.io.RandomAccessFile'.
** Any sql/jdbc solutions are out of scope for this project  
* The service must be able to handle concurrent API calls,
  even for the same customer and the same product,
  without causing any data inconsistencies.
  Data inconsistencies that pop up during testing are unacceptable and will fail the project
* The project must have a `README` file, containing:
** Team composition
** Instructions on how to build, and run, your service
** All (design) decisions you take,
  with reasonings  
** Clear documentation on how the 'service.db' file is structured.
* Test that your service will never return a 500+ ServerError
* The frontend is built by another team.
  Your focus is on writing a backend REST service.
  Your service API contract is already defined,
  as given in <<api-design>>

[[api-design]]
== API Design

=== Price notification Service

The model for your API is described in the `price-notification-service.xsd` file.

The frontend will do the following calls to your service:

[%autowidth.spread,cols="h,d"]
|===
|Method
|`GET`

|Path
|`/v1/customer/{customerId}/notifications`

|Accept
|`application/xml`

|Status 200
|Returns a NotificationList object containing a list of active Notifications that haven't been fired

|Functionality
|Retrieves all the notifications for the customer with the given customerId.
The functionality will always return with a list,
even if there are no notifications configured for the customer
|===

[%autowidth.spread,cols="h,d"]
|===
|Method
|`PUT`

|Path
|`/v1/customer/{customerId}/notifications/{ean}`

|Body
|A Notification object containing the ean, and the price

|Content-Type
|`application/xml`

|Status 201
|Operation successful, returns nothing

|Functionality
|Create or update notifications for products (eans).
If there is already a notification available for the given ean,
then that notification will be updated
|===

[%autowidth.spread,cols="h,d"]
|===
|Method
|`DELETE`

|Path
|`/v1/customer/{customerId}/notifications/{ean}`

|Body
|None

|Content-Type
|`application/xml`

|Status 204
|Notification successfully deleted

|Status 404
|No notification can be found for the customer with this ean

|Functionality
|Deletes the notification for the customer with the given ean
|===

=== Customer service

[%autowidth.spread,cols="h,d"]
|===
|Method
|`GET`

|Path
|`/v1/customer/`

|Content-Type
|`application/xml`

|Status 200
|Returns a CustomerList object containing a list of Customer objects

|Functionality
|Retrieves all customers.
The functionality will always return with a list,
even if there are no customers
|===

[%autowidth.spread,cols="h,d"]
|===
|Method
|`GET`

|Path
|`/v1/customer/{customerNumber}`

|Content-Type
|`application/xml`

|Status 200
|Returns a Customer object

|Status 404
|Customer does not exist

|Functionality
|Returns the specific customer
|===

=== Email service

[%autowidth.spread,cols="h,d"]
|===
|Method
|`PUT`

|Path
|`/v1/email`

|Body
|An Email object containing the receiver' emailaddress,
subject, and the body content

|Content-Type
|`application/xml`

|Status 202
|Operation successful, returns nothing

|Functionality
|Sents given email to receiver' emailaddress
|===

=== Product service

[%autowidth.spread,cols="h,d"]
|===
|Method
|`GET`

|Path
|`/v1/product/`

|Content-Type
|`application/xml`

|Status 200
|Returns a ProductList object containing a list of Product objects

|Functionality
|Retrieves all products.
The functionality will always return with a list,
even if there are no products
|===

[%autowidth.spread,cols="h,d"]
|===
|Method
|`GET`

|Path
|`/v1/product/{ean}`

|Content-Type
|`application/xml`

|Status 200
|Returns a Product object

|Status 404
|Product does not exist

|Functionality
|Returns the specific product
|===
