= Lab 1: Refactoring legacy code

In `labs/01-legacy-code` you can find the first lab.

.Project structure
----
.
├── src
│   ├── main
│   │   └── java
│   │       └── org
│   │           └── joyofcoding
│   │               └── objectcalisthenics
│   │                   ├── GildedRose.java
│   │                   └── Item.java
│   └── test
│       └── java
│           └── org
│               └── joyofcoding
│                   └── objectcalisthenics
│                       ├── assertions
│                       │   └── ItemsAssert.java
│                       └── GildedRoseTest.java
├── 01-legacy-code.gradle
└── README.adoc
----

The goal of this lab is to let you try out heuristics that allows
to guide refactoring efforts towards clean code and object oriented concepts.

We'll refactor the code in 4 steps:

1. Introduction
2. Move code to existing objects
3. Encapsulate primitives and collections
4. Make the business domain emerge

== Introduction

Hi and welcome to team Gilded Rose.
As you know,
we are a small inn with a prime location in a prominent city run by a friendly innkeeper named Allison.
We also buy and sell only the finest goods.
Unfortunately, our goods are constantly degrading in quality as they approach their sell by date.
We have a system in place that updates our inventory for us.
It was developed by a no-nonsense type named Leeroy,
who has moved on to new adventures.
Your task is to add the new feature to our system so that we can begin selling a new category of items.

First an introduction to our system:

- All items have a SellIn value which denotes the number of days we have to sell the item
- All items have a Quality value which denotes how valuable the item is
- At the end of each day our system lowers both values for every item

However, as usual, the original developers have left and there’s no reliable document about the business rules.
You’ll have to go with the code...

NOTE: Luckily there are basic unit-test.
      The tests make sure the application works as it should,
      and therefor *should not be touched during the refactoring*.

== Exercise 1: Move code to existing objects

The first step is to make sure all the code is in the right object or abstraction.
In terms of OO that implies that we encapsulate data so that refining
the rules around a particular piece of data is easy
(i.e. changing the least amount of code).
For instance,
code in class A that speaks about data in B should be in B.
*Move it there*.

*Heuristic*

* Start by identifying the lines that have the least amount of dependencies.
  That is the most indented piece of code.
  It is likely to work with only one object/variable.
** Now extend the zone as far as possible until you hit another dependency
*** If you have only one dependency, use rule 5 or 9
*** If you have two or more dependencies, try to reduce the number

*Object Calisthenics*

* Rule 5: One dot per line
* Rule 9: No getters/setters/properties

== Exercise 2: Encapsulate primitives and collections

Now that all logic is in the appropriate object or abstraction,
we'll have to create new objects that can receive data and related behavior.
In this phase we'll encapsulate primitives (rule 3),
but we could just as well encapsulate collections in so-called first class collections (rule 4).

*Heuristic*

* Now that the code is in the appropriate object/abstraction,
  use rules 3 and 4 to create new objects and abstractions

*Object Calisthenics*

* Rule 3: Wrap all primitives and Strings
* Rule 4: First class collections (wrap all collections)

== Exercise 3: Make the business domain emerge

Make the business domain as visible as possible in the code.

*Heuristic*

* Continue refactoring until all the other rules (1, 2, 6, 7, 8) are satisfied

*Object Calisthenics*

* Rule 1: One level of indentation per method
* Rule 2: Don’t use the ELSE keyword
* Rule 6: Don’t abbreviate
* Rule 7: Keep all entities small
* Rule 8: No classes with more than two instance variables

== Conclusion

The 9 Object Calisthenics rules:

1. One level of indentation per method
2. Don't use the ELSE keyword
3. Wrap all primitives and Strings
4. First class collections
5. One dot per line
6. Don't abbreviate
7. Keep all entities small
8. No classes with more than two instance variables
9. No getters/setters/properties

These rules help you create better, cleaner, software.
Does that mean you should always apply all of them?
In short, no.
Like everything in software,
it depends on the situation,
and the opinions,
of those creating and reviewing the code.
But keeping these rules in the back of your mind,
evaluating if you should apply them to the code you're working on,
that's the goal of these rules.

WARNING: Especially rule 7, 8, and 9, are commonly seen as extreme.
         It's good to use them to the letter in learning situations,
         so you experience them to the best.
