= Legacy Code

Code that does its thing,
but is old and/or isn't up to par with the latest code guidelines and principles,
is commonly marked as Legacy Code.
The same goes for code that isn't covered by tests.

When starting refactoring legacy code,
we ask our selves some of the following questions:

- Where to start?
- If I start here will it cause problems later on?
- I see 2-3 options, which one should I choose?

First and foremost,
find the smallest piece of code that you can start refactoring.
For that piece,
create unit tests which tests the boundaries and special cases.
Then, start refactoring!
Take very small steps,
create additional tests when needed,
and keep those tests green.

To help refactoring towards clean code and object oriented concepts,
there are the
link:legacy-code/DevelopersAnonymous-ObjectCalisthenics.pdf[9 Object Calisthenics rules]:

1. One level of indentation per method
2. Don't use the `else` keyword
3. Wrap all primitives and Strings
4. First class collections (wrap all collections)
5. One dot per line
6. Don't abbreviate
7. Keep all entities small
8. No classes with more than two instance variables
9. No getters/setters/properties

More info around these rules can be found at: http://williamdurand.fr/2013/06/03/object-calisthenics/

These rules are good practise for all code,
not only legacy code.

NOTE: These 9 Object Calisthenics rules, are "rules".
      In this lab the idea is that you apply these rules to the *max*,
      but this doesn't mean you _can_ apply it everywhere.
      There are situations where it simply doesn't make sense.

Next, some tips to help you apply the 9 rules.

== How to calculate the number of code dependencies

.Given code sample
[source,java,linenums]
----
places[currentPlayer] = places[currentPlayer] + diceResult;
if (places[currentPlayer] > 11)
    places[currentPlayer] = places[currentPlayer] - 12;
----

- Line 3 is the deepest nested code.
  It has 2 dependencies, namely: `places` and `currentPlayer`
- If we include line 2,
  we still find 2 dependencies, namely: `places` and `currentPlayer`
- If we include line 1,
  we find 3 dependencies, namely: `places`, `currentPlayer`, and `diceResult`

That's how you calculate the number of dependencies in a piece of code.

== How to reduce the number of code dependencies

=== Extract local variable

.This code depends on `items` and `i`
[source,java]
----
if (items.get(i).getQuality() > 0) {
----

.If we declare `item` above, the if statement has only one dependency: `item`
[source,java]
----
Item item = items.get(i);

if (item.getQuality() > 0) {
----

This is called the "extract local variable" refactoring.

=== Invert `if`-statement

.The code below has 2 dependencies: `quality` and `name`
[source,java]
----
if (quality > 0) {
    if (!name.equals("Sulfuras, Hand of Ragnaros")) {
        quality = quality - 1;
    }
}
----

.By simply inverting the if statements, we’re able to group the instructions about quality
[source,java]
----
if (!name.equals("Sulfuras, Hand of Ragnaros")) {
    if (quality > 0) {
        quality = quality - 1;
    }
}
----

This is called the "invert `if`-statement" refactoring.

== Wrap integer with domain concept

[source,java]
----
public class Discounter {
    private int discount;

    public int applyTo(int initialPrice) {
        return initialPrice - discount;
    }

    // ...
}
----

.Becomes
[source,java]
----
public class Discounter {
    private Money discount;

    public Money applyTo(Money initialPrice) {
        return initialPrice.minus(discount);
    }

    // ...
}

public class Money {
    private int discountInCents;

    // ...
}
----

If the variable of your primitive type has *behaviors*,
you MUST encapsulate it.
And this is especially true for *Domain Driven Design* (DDD).
DDD describes Value Objects like `Money`, or `Hour` for instance.

== How to get rid of `else`-statements

The `else` keyword is well-known as the `if`/`else` construct is built into nearly all programming languages.
Do you remember the last time you saw a nested conditional?
Did you enjoy reading it?
I don’t think so,
and that is exactly why it should be avoided.
As it is so easy to add a new branch to the existing code than refactoring it to a better solution,
you often end up with a really bad code.

Here some ways to remove the `else` keyword from your code.

=== Early Return

The condition can be either *optimistic*,
meaning you have conditions for your error cases and the rest of your method follows the default scenario,
or you can adopt a *defensive approach*
(somehow related to https://en.wikipedia.org/wiki/Defensive_programming[Defensive Programming]),
meaning you put the default scenario into a condition,
and if it is not satisfied,
then you return an error status.
This is better as it prevents potential issues you didn’t think about.

[source,java]
----
public boolean isValidEmail(String email) {
    if (validFormat(email)) {
        // do logic
    } else {
        return false;
    }
}
----

.Becomes
[source,java]
----
public boolean isValidEmail(String email) {
    if (!validFormat(email)) {
        return false;
    }
    // do logic
}
----

As an alternative,
you can *introduce a variable* in order to make your *return statement parameterizable*.
This is not always possible though.

Returning from a method as soon as possible,
keeps the code readable,
focused on the actual logic,
and minimally indented.

=== Polymorphism

Polymorphism is an alternative to `if`/`else`/`switch`-statements.
For instance,
it is possible to use the
http://www.oodesign.com/strategy-pattern.html[Strategy Pattern]
or inheritance to replace every clause in the control statement.

There are variations to how the "right" strategy is obtained, eg.:

* Caller provides the strategy (as a method argument)
* Strategy is memorised as member variable
* Strategy is obtained from a map (or any other lookup mechanism)

=== Null Object, Optional, or Empty list

A Null Object is an object with no referenced value or with defined neutral (`null`) behavior.

The
https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html[Java Optional]
, https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#emptyList()[Collections#emptyList()]
, https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#emptyMap()[Collections#emptyMap()]
, https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#emptySet()[Collections#emptySet()]
, https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#emptyListIterator()[Collections#emptyListIterator()]
, and https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#emptyEnumeration()[Collections#emptyEnumeration()]
, are all implementations of the Null Object provided by the Java language.

Using Null Object dramatically reduces the need for `null` checking.

.Example without Optional
[source,java]
----
SoundCard soundcard = ...;
if(soundcard != null){
  System.out.println(soundcard);
}
----

.Example with Optional
[source,java]
----
Optional<Soundcard> soundcard = ...;
soundcard.ifPresent(System.out::println);
----


//== Lab 1: Legacy Code
include::../../../../labs/01-legacy-code/README.adoc[leveloffset=+1]
